### ISSUE TITLE
Add starting page 

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#10]
when we open the JWOC site ,the starting page animation of JWOC logo  appears ,just like that add similar animation of (Logo spaceedu) when user opens website the Logo(spaceedu) animation should appear(time=1s) then after that main page will  appear.

**Comment by shahil-afroz** [comment]
what kind of techstack  or language we have to use for this? Can you kindly  elaborate this?

**Comment by 02shreyansh** [comment]
As it is a frontend project, you have to use HTML, CSS, and JavaScript.

**Comment by 02shreyansh** [comment]
Using these, you have to create a starting page opening animation, just like when you open the JWOC webpage. A starting animation of JWOC logo  appears for a few seconds.

**Comment by prasukjain07** [comment]
@02shreyansh 
I would like to work on this issue under JWOC, kindly assign this issue to me

**Comment by Sneha-Sonkar** [comment]
I would like to work on this issue under JWOC

**Comment by 02shreyansh** [comment]
@prasukjain07 ,Write your full name on discord channel(Landing-page); I have to assign it in Google Sheets.
