### ISSUE TITLE
Add a dedicated blog page for wormholes blog

### ISSUE THREAD

**Issue by PranavBarthwal** [02shreyansh/CODSOFT#102]
Add a dedicated blog page for wormholes blog.
on clicking read more user will be redirected to the blog page.

Please assign this to me under JWoC'24

**Comment by 02shreyansh** [comment]
@PranavBarthwal ,What do you actually want to do? Do you create a separate HTML page, or do you simply attach the link of wormholes in the "Read More" link?

**Comment by PranavBarthwal** [comment]
Separate page in our website only. 

> @PranavBarthwal ,What do you actually want to do? Do you create a separate HTML page, or do you simply attach the link of wormholes in the "Read More" link?
