### ISSUE TITLE
contact page 

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#11]
**Create a contact form within the main webpage itself. When the user clicks on 'Contact', it should scroll down to the contact section.**

**Comment by debuuuu007** [comment]
The contact button within the navbar in working fine. Can you elaborate the problem you are trying to say. So that I can understand more.

**Comment by 02shreyansh** [comment]
https://github.com/02shreyansh/CODSOFT/assets/137887705/d3628207-0265-4a96-8d19-127f3c97823e



like this......

**Comment by ogshashwat17** [comment]
i would like to try this problem but i am unaware of how it will work i can create a form

**Comment by TejaswaniVelugoti** [comment]
I am interested in contributing to this as a part of JWOC. Please assign it to me.

**Comment by prasukjain07** [comment]
Hey mentor, I would like to work on this issue, please assign this issue to me under JWOC

**Comment by singhcodes26** [comment]
i would like to work on this issue under JWOC

**Comment by TejaswaniVelugoti** [comment]
The contact button in the navigation menu is working as expected .Can you please tell me the exact requirement so that I can work accordingly.

**Comment by 02shreyansh** [comment]
@TejaswaniVelugoti, wait, wait. Are you viewing the portfolio repo? Because in the Landing Page repo, there is no contact in the navbar. The confusion arose because I included all three projects in the mentor registration.

correct repo :- https://github.com/02shreyansh/CODSOFT/tree/main/Landing%20page

this is correct repo ,You can also see it !

**Comment by TejaswaniVelugoti** [comment]
I have already done the PR and by mistake I have clicked on unassign me. Will it effect my score in JWOC

**Comment by vermaanurag1532** [comment]
please assign it to me i can do this for you

**Comment by 02shreyansh** [comment]
@TejaswaniVelugoti I am not sure about this ,But i have assigned your in Google sheet.
