### ISSUE TITLE
add footer section

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#12]

**Comment by debuuuu007** [comment]
I would like to work on that issue under JWOC.

**Comment by Aswinr24** [comment]
I would like to work on this issue under JWOC 24

**Comment by debuuuu007** [comment]
Hello sorry for late reply, 

What things you want to add in footer section, like social links, copyright or privacy policy or any other links?

**Comment by 02shreyansh** [comment]
@debuuuu007 All the necessary details.... Privacy policy and all that.... 
There should be a link of privacy policy

**Comment by debuuuu007** [comment]
Ok, i will start designing as well and coding and show it to you by tomorrow. Is that ok ?

**Comment by 02shreyansh** [comment]
okayy!

**Comment by Hacxmr** [comment]
Hey! @02shreyansh  I would like to contribute in this issue. Kindly assign me this task under JWOC.

**Comment by avanimehta11** [comment]
I would like to contribute to this issue under JWOC'24

**Comment by avanimehta11** [comment]
Would you mind taking a quick look at the footer I designed? I would greatly appreciate any feedback or suggestions for improvement.

https://github.com/02shreyansh/CODSOFT/assets/133508816/ee73f40c-1a51-4d17-b92f-2ca4e011e120

**Comment by 02shreyansh** [comment]
@avanimehta11 ,It looks good, just reduce the height a bit and add a line between the contact and footer.
