### ISSUE TITLE
Organize files and folders

### ISSUE THREAD

**Issue by Surajit0573** [02shreyansh/CODSOFT#122]
Currently, the project files and folders are disorganized and scattered. It has become quite challenging to both contribute to and read the project. 

![image](https://github.com/02shreyansh/CODSOFT/assets/111490250/ebab9df8-3e46-4ad2-a689-86ce3d8ae0ca)

Therefore, I intend to arrange all the files and folders in a way that makes them easily readable and contributable. I will also update the links used in the HTML files accordingly.

Assign me under JWOC 2024, if approved.

**Comment by kaif969** [comment]
please assign it to me under JWOC'2024.

**Comment by HARSH00M** [comment]
I can restructure in such a way that the repo will be easily understandable. So you can Assign this to me.

**Comment by 02shreyansh** [comment]
@kaif969 @HARSH00M, The first one to create a pull request without a merge conflict will get the point.
