### ISSUE TITLE
fix blog page 

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#124]
![Screenshot (1074)](https://github.com/02shreyansh/CODSOFT/assets/137887705/65434a9b-db3f-4944-b1c4-a875a213cb0b)

**Comment by PranavBarthwal** [comment]
I would like to fix this under jwoc

**Comment by PranavBarthwal** [comment]
Can I restyle the whole page?
there are many issues with current styling. If yes then also please consider increasing the difficulty tag.

(Colored boxes are for my reference, I'll keep in mind existing theme )

![Screenshot (143)](https://github.com/02shreyansh/CODSOFT/assets/110532770/04acf4f0-5896-49af-8696-0133174722b7)

![image](https://github.com/02shreyansh/CODSOFT/assets/110532770/3f1bf3ed-edcd-4381-ae45-9638c0b4e9fc)

**Comment by 02shreyansh** [comment]
Okay
