### ISSUE TITLE
Add Planets and Blog page 

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#13]

**Comment by SGCODEX** [comment]
Sir, I would like to work on this issue under JWOC

**Comment by Anushkabh** [comment]
Hey @02shreyansh  ,
I would like to work on this issue.
Would really appreciate if you assign me this issue .

**Comment by prasukjain07** [comment]
Hello mentor, I would like to work on this issue, please assign this issue to me under JWOC

**Comment by SGCODEX** [comment]
Thank you sir for assigning me, we have three days for this right?

**Comment by 02shreyansh** [comment]
Yes!

**Comment by 02shreyansh** [comment]
@SGCODEX status of PR?

**Comment by SGCODEX** [comment]
Sir will.be submitting today

**Comment by 02shreyansh** [comment]
Okay!

**Comment by 02shreyansh** [comment]
@SGCODEX

**Comment by vishal2005025** [comment]
I have read the issue and I want to work on it .
please assign it to me under JWOC'2024.

**Comment by vishal2005025** [comment]
sir , I have completed the issue and created pull request.
please check..

**Comment by 02shreyansh** [comment]
@vishal2005025 ,Please,write your full name and Github ID on Discord channel(Landing-page)

Great Work @vishal2005025

**Comment by vishal2005025** [comment]
Name : VISHAL MALYAN 
Github Id :  https://github.com/vishal2005025

**Comment by vishal2005025** [comment]
sir, I can't find the discord channel of landing page.
please provide the link of discord channel..
