### ISSUE TITLE
I want to add animation to the Landing page website

### ISSUE THREAD

**Issue by Sneha123-zudo** [02shreyansh/CODSOFT#177]
PLease assign me this issue under JWOC'24

**Comment by 02shreyansh** [comment]
@Sneha123-zudo ,In which part will you add animation? Please let me know

**Comment by Sneha123-zudo** [comment]
I will add animations to the other pages except the main page , please assign me this issue under JWOC'24

**Comment by 02shreyansh** [comment]
You have already been assigned
