### ISSUE TITLE
Responsive 

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#197]
# Make index.html responsive

**Comment by thatguywhocode** [comment]
Hey @02shreyansh , assign me this task under JWOC.

**Comment by 02shreyansh** [comment]
Hello @thatguywhocode, could you replicate the desktop view animation in the mobile version? If that's not feasible, please create a hamburger menu and replace the animation with a single space-themed image featuring planets. Ensure the other sections are made presentable as well.

**Comment by 02shreyansh** [comment]
@thatguywhocode ,PR status?

**Comment by thatguywhocode** [comment]
I am facing issues to implement hamburger menu, if there are more things please let me know
