### ISSUE TITLE
Hover button in landing page, Blog from the nav bar isnt working either 

### ISSUE THREAD

**Issue by thesri** [02shreyansh/CODSOFT#2]
selecting blog doesnt provide any information, and the hover button in the landing page on enroll would make it look a way better

**Comment by thesri** [comment]
please kindly assign this issue to me , for jwoc 2024

**Comment by thesri** [comment]
Please reassign it to me :)

**Comment by 02shreyansh** [comment]
Already assigned

**Comment by thesri** [comment]
> Already assigned

should i start working on it now

**Comment by 02shreyansh** [comment]
@thesri, no, because this was raised by you before January 15th. According to the rules, it is considered invalid. From now on, issues raised by you will be considered valid.
