### ISSUE TITLE
Adding backend for the Enroll form

### ISSUE THREAD

**Issue by MaruthiSingh** [02shreyansh/CODSOFT#20]
New Update -
Adding google sheet as backend for the Enroll form

Expected Output -

https://github.com/02shreyansh/CODSOFT/assets/103304179/8ec9e233-1714-43df-96e6-63229440fa7a

I would like to work on this issue under JWOC

**Comment by 02shreyansh** [comment]
@MaruthiSingh, That's a good idea. Will you be able to add the email link? When the submit button is clicked, the user should receive an email confirming successful enrollment, and the enrollment data should also be added to Google as proposed by you.

**Comment by naikmubashir** [comment]
@02shreyansh    Assign me this issue , I would like to work on it.

**Comment by MaruthiSingh** [comment]
Hello @02shreyansh, 
Can you tell the email template to send the mail, please.

**Comment by 02shreyansh** [comment]
@MaruthiSingh 
![Screenshot (1072)](https://github.com/02shreyansh/CODSOFT/assets/137887705/9c639773-dff8-4aca-9d54-74b579fa85eb)
something like this

**Comment by 02shreyansh** [comment]
@Hacxmr ,status of PR?

**Comment by Hacxmr** [comment]
Hey! @02shreyansh I have added a Google sheet to the form. working on sending an acknowledgment of the confirmation

**Comment by 02shreyansh** [comment]
Okay!

**Comment by 02shreyansh** [comment]
@Hacxmr ,Please do it  ASAP

**Comment by 02shreyansh** [comment]
@Hacxmr ,hurry up !! do it ASAP
