### ISSUE TITLE
Organise all the files properly !

### ISSUE THREAD

**Issue by SohanRC** [02shreyansh/CODSOFT#209]
Organise all the files in the Landing Page properly . It will make the project more professional ! Make seperate sections for html files , css files , javascript files , images , etc.

**Comment by AftabMankapure** [comment]
@02shreyansh  this issue is solved in PR of issue #210  PR #214

**Comment by SohanRC** [comment]
@02shreyansh Yes , this is a multiple issue of same type ! But i created this same issue first ! So I think that you have mistakenly assigned both issues of same type !

**Comment by SohanRC** [comment]
@AftabMankapure Bro i had created the same issue first !

**Comment by 02shreyansh** [comment]
@SohanRC, you can also work on this issue, as some of the functionality has been compromised. You could fix them.

**Comment by SohanRC** [comment]
Okk @02shreyansh

**Comment by AftabMankapure** [comment]
@SohanRC  sorry for that i dont check it next time i will take care about it

**Comment by SohanRC** [comment]
> @SohanRC sorry for that i dont check it next time i will take care about it

Its ok bro !
