### ISSUE TITLE
Bug: Heroright animation not visible.

### ISSUE THREAD

**Issue by avanimehta11** [02shreyansh/CODSOFT#26]
The pop-up animation of heroright content doesn't appear when the website is loaded due to the loader as issue #22 was closed alongside issue #5, the changes done could not be reflected.
Can you please assign me to contribute to this issue under JWOC'24.

**Comment by 02shreyansh** [comment]
@avanimehta11 there is no in loader ,it is working fine .
but yes, heroright animation is not working.

**Comment by avanimehta11** [comment]
Can you please assign the issue to me under JWOC'24 so that I can contribute to it.

**Comment by 02shreyansh** [comment]
Thank You @avanimehta11
