### ISSUE TITLE
Responsive 

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#3]
MAKE THIS LANDING PAGE RESPONSIVE

**Comment by Prithwi32** [comment]
Hello @02shreyansh please could you assign this task to me under JWoC 2024

**Comment by 02shreyansh** [comment]
Okay!

**Comment by Prithwi32** [comment]
hello @02shreyansh  I would like to work on that issue under JWOC ...

**Comment by Sneha-Sonkar** [comment]
I would like to work on this issue under JWOC

**Comment by 02shreyansh** [comment]
@shahil-afroz ,Status of PR??

**Comment by Prithwi32** [comment]
@02shreyansh I would Like to work on this issue under JWOC

**Comment by 02shreyansh** [comment]
@Prithwi32 ,status of PR?

**Comment by Prithwi32** [comment]
> @Prithwi32 ,status of PR?
could you give me some more days time, I'm bit busy with college works

**Comment by 02shreyansh** [comment]
@Prithwi32 ,status of PR?

**Comment by Prithwi32** [comment]
> @Prithwi32 ,status of PR?

@02shreyansh done with html, css part
need to add some javascript functionality to openup menu
![image](https://github.com/02shreyansh/CODSOFT/assets/115262737/21865134-df27-40c5-9f95-bd7ca99c501e)

**Comment by 02shreyansh** [comment]
okay

**Comment by SohanRC** [comment]
@02shreyansh Please assign me this issue under JWOC 2024. !!
