### ISSUE TITLE
style Contact Page

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#34]

**Comment by vishal2005025** [comment]
I have read the issue and I want to work on it .
please assign it to me under JWOC'2024.

**Comment by Rishav9911** [comment]
hey, if this is available, I would like to work on this issue and make a seperate page for contact us with better UI.

**Comment by vishal2005025** [comment]
I am working on this issue ..

**Comment by vermaanurag1532** [comment]
please assign it to me

**Comment by vermaanurag1532** [comment]
Please Accept my PR

**Comment by 02shreyansh** [comment]
@vermaanurag1532 ,I need better style on the Contact Page.


@vishal2005025, I have raised a new issue regarding the Contact page. Therefore, you can comment on that issue, and I will assign it to you
