### ISSUE TITLE
Adding Navbar on login and Enroll page

### ISSUE THREAD

**Issue by Rishav9911** [02shreyansh/CODSOFT#37]
Adding a navbar from homepage on login and enroll page for easy navigation from those pages to another. kindly assign me this issue under JWOC.

**Comment by Rishav9911** [comment]
hey @02shreyansh , I have made the above mentioned changes  and added a HOME button in navbar in both pages for easy navigation. I am making a  pull request for the changes, kindly review it.

![Screenshot 2024-01-21 200626](https://github.com/02shreyansh/CODSOFT/assets/133174630/6c5f91ca-81c6-4121-b582-1fc0dd99e148)

![Screenshot 2024-01-21 200615](https://github.com/02shreyansh/CODSOFT/assets/133174630/b5e58126-3a52-457c-a7af-c3b5d176ed2d)

**Comment by 02shreyansh** [comment]
@Rishav9911 ,Please ,Write your full name and github Id on discord channel(Landing-page)
