### ISSUE TITLE
add Login page In Nav-bar 

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#4]
**This login page should open in separate or new tab .**

**Comment by Aryan12612** [comment]
Hello Mentor Could you assign me the issue when coding period starts?

**Comment by 02shreyansh** [comment]
okay!

**Comment by Sruti-sahini** [comment]
Hello @02shreyansh!
I have a good hold in web development.
Could you please assign me this issue?
I am JWoC'24

**Comment by thatguywhocode** [comment]
Hello @02shreyansh  , I would like to work on this issue under JWOC.

**Comment by Anushkabh** [comment]
Hey @02shreyansh 
I would like to work on this issue.
Would really appreciate if you assign me this issue

**Comment by thatguywhocode** [comment]
Hey @02shreyansh , can you please elaborate the issue, i need to create login tag in navbar that sends user to another tab ?

**Comment by 02shreyansh** [comment]
Yes, @thatguywhocode  another tab will appear. Try to use the glassmorphism effect if you can; otherwise, use your own style."

**Comment by thatguywhocode** [comment]
Hey @02shreyansh , I have solved the issue and created pr under JWOC.

**Comment by 02shreyansh** [comment]
@thatguywhocode ,write your full name & Github id on discord channel(Landing page), I have to assign it in Google sheet.

**Comment by DarshSohaliya** [comment]
I would like to work on that issue under JWOC
