### ISSUE TITLE
Animate  (class=heroright  ,content) Like class=workingarea

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#5]
**Animate the content of heroright ,just like  content of workingarea**

**Comment by Anushkabh** [comment]
Hey @02shreyansh ,
I would like to work on this issue.
Would really appreciate if you assign me this issue .

**Comment by 02shreyansh** [comment]
@Anushkabh 
Write a keyword under JWOC to contribute to this issue.

**Comment by avanimehta11** [comment]
Hello @02shreyansh,
I would like to contribute to this issue under JWOC'24.

**Comment by Anushkabh** [comment]
Hey @02shreyansh ,
I would like to work on this issue under JWOC'24

**Comment by 02shreyansh** [comment]
@avanimehta11 
write your full name on discord channel(Landing-page),I have to assign it in Google Sheet.
