### ISSUE TITLE
Contact Page 

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#52]

**Comment by vishal2005025** [comment]
I would like to work on this issue.
Please assign it to me under JWOC'2024.

**Comment by vishal2005025** [comment]
Sir , I work is almost done I will created pr by tomorrow..

**Comment by vishal2005025** [comment]
sir , I have created pr ..

**Comment by 02shreyansh** [comment]
@vishal2005025 ,Great Work!

**Comment by vishal2005025** [comment]
Sir , please change the label to hard .. please..

**Comment by 02shreyansh** [comment]
Okay
