### ISSUE TITLE
Add Menu 

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#58]
Place all the Navbar content inside the Menu except the Enroll Option.

**Comment by avanimehta11** [comment]
I would like to contribute to this issue under JWOC'24

**Comment by thesri** [comment]
@02shreyansh please assign this under jwoc 2024, if the assigned mentee didnt do it in time

**Comment by 02shreyansh** [comment]
@avanimehta11 ,Status of PR?

**Comment by avanimehta11** [comment]
@02shreyansh 
Please assign it to someone else...sorry I couldn't complete it as I am sick.

**Comment by Sneha123-zudo** [comment]
I am intrested in this issue please assign me this issue.

**Comment by 02shreyansh** [comment]
Okay ! @avanimehta11

**Comment by thesri** [comment]
> Okay ! @avanimehta11

i haved commented first with jwoc tag isnt it that it should be assigned to me >?

**Comment by 02shreyansh** [comment]
@Sneha123-zudo ,status of pR?

**Comment by Sneha123-zudo** [comment]
I will make the PR ....I am working on it

**Comment by 02shreyansh** [comment]
@Sneha123-zudo, please do it quickly.

**Comment by PranavBarthwal** [comment]
@02shreyansh PLease assign this to me, I would like to work on itu under jwoc'24
