### ISSUE TITLE
add enroll page

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#6]
**Add the enroll page ,when user click on it ,a separate page should appear and contain the enrollment form .**

**Comment by ayesha-2101** [comment]
I am willing t o work on this as well on the frontend part. Please assign it to me @02shreyansh

**Comment by 02shreyansh** [comment]
okay!

**Comment by ogshashwat17** [comment]
i would love to work on this project

**Comment by TejaswaniVelugoti** [comment]
I am interested in contributing to this as a part of JWOC. Please assign it to me.

**Comment by TejaswaniVelugoti** [comment]
I am interested in contributing to this as a part of JWOC. Please assign this issue to me

**Comment by 02shreyansh** [comment]
@TejaswaniVelugoti ,Write your full name & github Id on discord channel(Landing-Page); I have to assign it in Google Sheets.
