### ISSUE TITLE
fix:  Website logo

### ISSUE THREAD

**Issue by avanimehta11** [02shreyansh/CODSOFT#62]
It seems there are discrepancies with the website logo across pages compared to the one displayed during the loading process. Additionally, the rotating effect causing the logo to disappear is a prime example of poor user interface design.
![web-logo displayed](https://github.com/02shreyansh/CODSOFT/assets/133508816/bc359998-12b1-4694-b2fc-41ba324e9df8)

I would replace the above with the one you provided earlier-
![image](https://github.com/02shreyansh/CODSOFT/assets/133508816/947505e4-e314-4617-8e26-fa8eed1872b9)

I would like to contribute to this issue under JWOC'24.

**Comment by 02shreyansh** [comment]
@avanimehta11 ,Status of PR?
