### ISSUE TITLE
fix the nav bar

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#7]

**Comment by ayesha-2101** [comment]
I am willing to work on this project. Please assign it to me @02shreyansh

**Comment by debuuuu007** [comment]
I would like to work on that issue under JWOC.

**Comment by ayesha-2101** [comment]
I am willing to work on this issue under JWOC. Please assign it to me @02shreyansh

**Comment by Aswinr24** [comment]
I would like to work on this issue under JWOC 24

**Comment by ayesha-2101** [comment]
@02shreyansh, what changes do I need to make in the nav bar? The issues that I can see are 
(a) The nav bar is fixed. 
(b) The CSS of the nav bar can be improved 
(c) The enroll button is not clickable

**Comment by 02shreyansh** [comment]
@ayesha-2101 Enhance the CSS of the navbar, add animation to it, make it more attractive. Apply CSS to the anchor tags and add some effects.

**Comment by 02shreyansh** [comment]
@ayesha-2101, Since this is an easy issue, you only have a few hours left to complete it.

**Comment by ayesha-2101** [comment]
@02shreyansh I was near completion

**Comment by ayesha-2101** [comment]
@02shreyansh can you reassign it for a day to me as you have unassigned everyone

**Comment by ayesha-2101** [comment]
I have added animation to the logo in the nav bar 
I have added a glow effect to anchor tags for better readability 
Changed the CSS of the button 
Added a meteor favicon 
Should I raise the PR? @02shreyansh 

https://github.com/02shreyansh/CODSOFT/assets/112239598/27e7401e-80f5-476e-a822-ca5f34604f77

**Comment by 02shreyansh** [comment]
@ayesha-2101 ,Yes ofcourse
