### ISSUE TITLE
Add ticket booking page

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#8]
Ticket Booking page should contain the list of various shows and videos and live stream and their respective pricing also both in online or offline mode ,It also contain the option to attend the shows etc in online or offline mode .If user click any of the list item it redirect to new page of their respective item and user have to fill the ticket form

**Comment by suruchichoudhary122** [comment]
would like to work on this issue.

**Comment by suruchichoudhary122** [comment]
I would like to work on this issue under JWOC'24.

**Comment by 02shreyansh** [comment]
@suruchichoudhary122  ,status of PR??

**Comment by Hacxmr** [comment]
Hey! @02shreyansh I would want to contribute to this issue. Assign me the same under JWOC'24

**Comment by vishal2005025** [comment]
Sir, I would like to work in this Issue.
Please assign it to me under JWOC'2024..

**Comment by vishal2005025** [comment]
Sir , please assign it to me.....
