### ISSUE TITLE
Make Contact Us form functional 

### ISSUE THREAD

**Issue by PranavBarthwal** [02shreyansh/CODSOFT#81]
I would like to make the existing contact us form functional.
Please assign this to me under JWOC'24. And please drop your email too with which you want it to be connected.

**Comment by PranavBarthwal** [comment]
@02shreyansh Can you please share your gmail id, so that I can start working on this issue.

**Comment by 02shreyansh** [comment]
02.shreyansh.10@gmail.com

**Comment by PranavBarthwal** [comment]
Am I allowed to make UI changes to the form?

**Comment by 02shreyansh** [comment]
@PranavBarthwal ,Yes you can
