### ISSUE TITLE
Add the Proper readme.md file in it 

### ISSUE THREAD

**Issue by 02shreyansh** [02shreyansh/CODSOFT#9]

**Comment by ayesha-2101** [comment]
@02shreyansh  I am a student at IIT Patna, and I am well-versed in web development. I wanted to work on this issue. Please assign it to me.

**Comment by Sneha6003** [comment]
https://github.com/02shreyansh/CODSOFT/issues/9

**Comment by Sneha6003** [comment]
I would like to work on that issue under JWOC.

**Comment by k3s1** [comment]
assign me this issue under JWOC

**Comment by 02shreyansh** [comment]
@Sneha6003 Write your full name; I have to assign it in Google Sheets.

**Comment by Sneha6003** [comment]
Sneha Singh
@02shreyansh
