### ISSUE TITLE
Add a blog page about "Aditya L1"

### ISSUE THREAD

**Issue by Surajit0573** [02shreyansh/CODSOFT#99]
I want to add a new blog about "Aditya L1" which will accessible through read more section, which is currently empty. 

![image](https://github.com/02shreyansh/CODSOFT/assets/111490250/804126e1-6b5d-4920-8a03-b67f89641e74)

Please assign me under JWOC 2024, if approved.

**Comment by 02shreyansh** [comment]
@Surajit0573 ,Do you create a separate HTML page, or do you simply attach the link of Aditya-L1 in the "Read More" link?

**Comment by Surajit0573** [comment]
Separate html page
